import { FamilyLink, FamilyNode, RelativeDirection } from '../types/graph';
import { kinshipLinksFromRows, personsFromRows } from './treeRecordRows';

export type TreeRecordErrorKind = 'refused' | 'not-authorized' | 'network' | 'conflict' | 'unknown';

export class TreeRecordError extends Error {
  readonly kind: TreeRecordErrorKind;
  readonly status?: number;

  constructor(kind: TreeRecordErrorKind, message: string, status?: number) {
    super(message);
    this.name = 'TreeRecordError';
    this.kind = kind;
    this.status = status;
  }
}

export function isTreeRecordError(err: unknown): err is TreeRecordError {
  return err instanceof TreeRecordError;
}

export interface TreeRecordIdentity {
  userId: string;
  isAdmin: boolean;
  sessionToken?: string | null;
}

export interface TreeRecordConfig {
  supabaseUrl?: string;
  supabaseKey?: string;
  fetch?: typeof fetch;
}

export interface AddPersonLinkSpec {
  targetId: string;
  relation: RelativeDirection;
  parentRole?: 'mother' | 'father' | null;
}

export interface AddPersonParams {
  /**
   * The Person's uuid, generated by the caller so a Spawn can be keyed on it
   * before the network answers (LIN-58's D11). Omitted, the database mints one.
   */
  id?: string;
  firstName: string;
  paternalCluster?: string | null;
  maternalCluster?: string | null;
  /**
   * If present, creates and links atomically via `create_relative_secure` RPC.
   * If absent, creates a standalone Person via REST `POST /nodes` (admin only).
   */
  link?: AddPersonLinkSpec;
}

export interface AddLinkParams {
  sourceId: string;
  targetId: string;
  type: 'parent' | 'marriage' | 'divorce';
  parentRole?: 'mother' | 'father' | null;
}

export interface EditPersonParams {
  id: string;
  firstName?: string;
  paternalCluster?: string | null;
  maternalCluster?: string | null;
}

export interface EditLinkParams {
  id: string;
  sourceId?: string;
  targetId?: string;
  type?: 'parent' | 'marriage' | 'divorce';
  parentRole?: 'mother' | 'father' | null;
}

export interface RemovePersonParams {
  id: string;
}

export interface RemoveLinkParams {
  id: string;
}

/**
 * What a write reported back: the rows the Tree Record accepted, in the
 * vocabulary the rest of the app reads. ADR-0003 fixed the six operations and
 * the error kinds and left this unspecified, so nothing optimistic could be
 * confirmed from a response (LIN-64).
 *
 * One shape for all six operations: a caller folding a write into its own copy
 * of the record never has to know which transport the write took, and a
 * `sibling` addition — several Kinship Links from one call — needs no special
 * case.
 */
export interface ConfirmedRows {
  persons?: FamilyNode[];
  links?: FamilyLink[];
  removedPersonIds?: string[];
  removedLinkIds?: string[];
}

/**
 * `addLink` alone has a third outcome. `link_existing_relative_secure` can
 * accept a write and insert nothing, because the Kinship Link already existed;
 * empty `links` on its own could not tell that apart from a server that wrote
 * something and declined to say what (LIN-58's D10, ADR-0008).
 */
export interface AddLinkResult extends ConfirmedRows {
  alreadyConnected: boolean;
}

export interface TreeRecord {
  addPerson(params: AddPersonParams): Promise<ConfirmedRows>;
  addLink(params: AddLinkParams): Promise<AddLinkResult>;
  editPerson(params: EditPersonParams): Promise<ConfirmedRows>;
  editLink(params: EditLinkParams): Promise<ConfirmedRows>;
  removePerson(params: RemovePersonParams): Promise<ConfirmedRows>;
  removeLink(params: RemoveLinkParams): Promise<ConfirmedRows>;
}

/**
 * Named edge helper: converts a Relative Direction (relative to an anchor target)
 * into an absolute Kinship Link specification.
 */
export function relativeToKinshipLink(
  anchorTargetId: string,
  otherNodeId: string,
  relation: RelativeDirection,
  parentRole?: 'mother' | 'father' | null
): AddLinkParams {
  switch (relation) {
    case 'child':
      return {
        sourceId: anchorTargetId,
        targetId: otherNodeId,
        type: 'parent',
        parentRole: parentRole ?? null,
      };
    case 'parent':
      return {
        sourceId: otherNodeId,
        targetId: anchorTargetId,
        type: 'parent',
        parentRole: parentRole ?? null,
      };
    case 'spouse':
      return {
        sourceId: anchorTargetId,
        targetId: otherNodeId,
        type: 'marriage',
        parentRole: null,
      };
    case 'sibling':
      throw new TreeRecordError(
        'refused',
        'Sibling is a composite relationship derived from shared parents; it cannot be converted to a single direct Kinship Link.'
      );
  }
}

function resolveEnv(config?: TreeRecordConfig) {
  const supabaseUrl = config?.supabaseUrl ?? (typeof import.meta !== 'undefined' ? import.meta.env?.VITE_SUPABASE_URL : undefined) ?? '';
  const supabaseKey = config?.supabaseKey ?? (typeof import.meta !== 'undefined' ? import.meta.env?.VITE_SUPABASE_ANON_KEY : undefined) ?? '';
  const fetchFn = config?.fetch ?? fetch;
  return { supabaseUrl, supabaseKey, fetchFn };
}

function buildHeaders(identity: TreeRecordIdentity, supabaseKey: string, prefer?: string): HeadersInit {
  const authToken = identity.sessionToken || supabaseKey;
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
  };
  if (supabaseKey) {
    headers['apikey'] = supabaseKey;
  }
  if (authToken) {
    headers['Authorization'] = `Bearer ${authToken}`;
  }
  if (prefer) {
    headers['Prefer'] = prefer;
  }
  return headers;
}

function parseErrorMessage(text: string, status: number): string {
  try {
    const j = JSON.parse(text) as { message?: string; error?: string; hint?: string };
    if (j.message) return String(j.message);
    if (j.error) return String(j.error);
    if (j.hint) return String(j.hint);
  } catch {
    /* ignore */
  }
  return text || `Request failed (${status})`;
}

/** The JSON envelope the three `*_secure` RPCs return. */
interface RpcEnvelope {
  success?: boolean;
  message?: string;
  new_node_id?: string;
  already_connected?: boolean;
  nodes?: unknown;
  links?: unknown;
  removed_link_ids?: unknown;
}

/**
 * An RPC reports failure inside a 200 envelope, so the discriminant has to come
 * from the message. `duplicate key` became reachable when Person uuids moved to
 * the client (LIN-58's D11): a colliding uuid fails on the primary key.
 */
function rpcFailureKind(message: string): TreeRecordErrorKind {
  const lower = message.toLowerCase();
  if (lower.includes('unauthorized')) return 'not-authorized';
  if (lower.includes('duplicate') || lower.includes('already exists')) return 'conflict';
  return 'refused';
}

/**
 * A 2xx body the seam cannot read is not a failed write: the row is in the
 * database and only the confirmation is missing. Raising `network` would tell
 * the caller the write did not happen, which is the one thing we know is false
 * — and LIN-58's sequencer reverts a Pending Change on a rejection. So this is
 * `unknown`: reload, do not assume.
 */
function unreadable(detail: string): TreeRecordError {
  return new TreeRecordError('unknown', `The write was accepted but ${detail}`);
}

/** The rows PostgREST returns under `Prefer: return=representation`. */
async function readRows(res: Response): Promise<unknown[]> {
  const text = await res.text().catch(() => '');
  if (!text) {
    throw unreadable('the server returned no rows.');
  }
  try {
    const parsed: unknown = JSON.parse(text);
    return Array.isArray(parsed) ? parsed : [parsed];
  } catch {
    throw unreadable('its response could not be read.');
  }
}

/** The JSON envelope an RPC returns, already read off the response. */
function parseRpcEnvelope(text: string): RpcEnvelope {
  try {
    return text ? (JSON.parse(text) as RpcEnvelope) : {};
  } catch {
    throw unreadable('its response could not be read.');
  }
}

async function handleResponseError(res: Response): Promise<never> {
  const text = await res.text().catch(() => '');
  const message = parseErrorMessage(text, res.status);
  const isConflict = res.status === 409 || message.toLowerCase().includes('duplicate') || message.toLowerCase().includes('conflict');

  if (res.status === 401 || res.status === 403) {
    throw new TreeRecordError('not-authorized', message, res.status);
  }
  if (isConflict) {
    throw new TreeRecordError('conflict', message, res.status);
  }
  throw new TreeRecordError('network', message, res.status);
}

export function createTreeRecord(
  identity: TreeRecordIdentity,
  config?: TreeRecordConfig
): TreeRecord {
  const { supabaseUrl, supabaseKey, fetchFn } = resolveEnv(config);

  const addPerson = async (params: AddPersonParams): Promise<ConfirmedRows> => {
    const sanitizedName = params.firstName.trim().slice(0, 200);
    if (!sanitizedName) {
      throw new TreeRecordError('refused', 'Name cannot be empty.');
    }

    if (params.link) {
      // Relative creation via RPC create_relative_secure
      const bodyPayload: Record<string, unknown> = {
        new_first_name: sanitizedName,
        rel_type: params.link.relation,
        target_node_id: params.link.targetId,
        creator_id: identity.userId,
      };
      if (params.link.relation === 'child' && params.link.parentRole) {
        bodyPayload.p_parent_role = params.link.parentRole;
      }
      if (params.id) {
        bodyPayload.p_new_node_id = params.id;
      }

      let res: Response;
      try {
        res = await fetchFn(`${supabaseUrl}/rest/v1/rpc/create_relative_secure`, {
          method: 'POST',
          headers: buildHeaders(identity, supabaseKey),
          body: JSON.stringify(bodyPayload),
        });
      } catch (err) {
        throw new TreeRecordError('network', err instanceof Error ? err.message : 'Network request failed');
      }

      if (!res.ok) {
        await handleResponseError(res);
      }

      const result = parseRpcEnvelope(await res.text().catch(() => ''));

      if (result.success === false) {
        const msg = result.message || 'Failed to create relative.';
        throw new TreeRecordError(rpcFailureKind(msg), msg);
      }

      // The Person's two cluster fields are derived server-side from the anchor
      // and the anchor's spouse, so an envelope without rows cannot be
      // reconstructed from what was sent — and it is not a confirmation.
      const persons = personsFromRows(result.nodes);
      if (persons.length === 0) {
        throw unreadable('the server did not report the Person it created.');
      }

      return { persons, links: kinshipLinksFromRows(result.links) };
    }

    // Standalone node creation via REST POST /nodes (admin only)
    if (!identity.isAdmin) {
      throw new TreeRecordError('refused', 'Only administrators can create standalone persons without a link.');
    }

    const payload: Record<string, unknown> = {
      first_name: sanitizedName,
      paternal_family_cluster: params.paternalCluster?.trim().slice(0, 100) || null,
      maternal_family_cluster: params.maternalCluster?.trim().slice(0, 100) || null,
      created_by_user_id: identity.userId,
    };
    if (params.id) {
      payload.id = params.id;
    }

    let res: Response;
    try {
      res = await fetchFn(`${supabaseUrl}/rest/v1/nodes`, {
        method: 'POST',
        headers: buildHeaders(identity, supabaseKey, 'return=representation'),
        body: JSON.stringify(payload),
      });
    } catch (err) {
      throw new TreeRecordError('network', err instanceof Error ? err.message : 'Network request failed');
    }

    if (!res.ok) {
      await handleResponseError(res);
    }

    return { persons: personsFromRows(await readRows(res)) };
  };

  const addLink = async (params: AddLinkParams): Promise<AddLinkResult> => {
    if (identity.isAdmin) {
      // Admin: REST POST /links
      const payload = {
        source_node_id: params.sourceId,
        target_node_id: params.targetId,
        type: params.type,
        parent_role: params.type === 'parent' ? (params.parentRole ?? null) : null,
        created_by_user_id: identity.userId,
      };

      let res: Response;
      try {
        res = await fetchFn(`${supabaseUrl}/rest/v1/links`, {
          method: 'POST',
          headers: buildHeaders(identity, supabaseKey, 'return=representation'),
          body: JSON.stringify(payload),
        });
      } catch (err) {
        throw new TreeRecordError('network', err instanceof Error ? err.message : 'Network request failed');
      }

      if (!res.ok) {
        await handleResponseError(res);
      }
      return { links: kinshipLinksFromRows(await readRows(res)), alreadyConnected: false };
    }

    // Non-admin: Route to link_existing_relative_secure RPC
    if (params.type === 'divorce') {
      throw new TreeRecordError('refused', 'Only administrators can record a divorce.');
    }

    let relType: 'spouse' | 'child';
    let existingNodeId: string;
    let targetNodeId: string;

    if (params.type === 'marriage') {
      relType = 'spouse';
      targetNodeId = params.sourceId;
      existingNodeId = params.targetId;
    } else {
      // parent link: sourceId is parent, targetId is child
      // link_existing_relative_secure with rel_type: 'child' sets source_node_id = target_node_id and target_node_id = existing_node_id
      relType = 'child';
      targetNodeId = params.sourceId;
      existingNodeId = params.targetId;
    }

    const payload: Record<string, unknown> = {
      existing_node_id: existingNodeId,
      rel_type: relType,
      target_node_id: targetNodeId,
      creator_id: identity.userId,
    };
    if (relType === 'child' && params.parentRole) {
      payload.p_parent_role = params.parentRole;
    }

    let res: Response;
    try {
      res = await fetchFn(`${supabaseUrl}/rest/v1/rpc/link_existing_relative_secure`, {
        method: 'POST',
        headers: buildHeaders(identity, supabaseKey),
        body: JSON.stringify(payload),
      });
    } catch (err) {
      throw new TreeRecordError('network', err instanceof Error ? err.message : 'Network request failed');
    }

    if (!res.ok) {
      await handleResponseError(res);
    }

    const result = parseRpcEnvelope(await res.text().catch(() => ''));

    if (result.success === false) {
      const msg = result.message || 'Failed to link relative.';
      throw new TreeRecordError(rpcFailureKind(msg), msg);
    }

    return {
      links: kinshipLinksFromRows(result.links),
      alreadyConnected: result.already_connected === true,
    };
  };

  const editPerson = async (params: EditPersonParams): Promise<ConfirmedRows> => {
    const updateData: Record<string, unknown> = {};

    if (params.firstName !== undefined) {
      const sanitizedName = params.firstName.trim().slice(0, 200);
      if (!sanitizedName) {
        throw new TreeRecordError('refused', 'Name cannot be empty.');
      }
      updateData.first_name = sanitizedName;
    }

    if (identity.isAdmin) {
      if (params.paternalCluster !== undefined) {
        updateData.paternal_family_cluster = params.paternalCluster ? params.paternalCluster.trim().slice(0, 100) : null;
      }
      if (params.maternalCluster !== undefined) {
        updateData.maternal_family_cluster = params.maternalCluster ? params.maternalCluster.trim().slice(0, 100) : null;
      }
    }

    const lid = encodeURIComponent(params.id);
    let res: Response;
    try {
      res = await fetchFn(`${supabaseUrl}/rest/v1/nodes?id=eq.${lid}`, {
        method: 'PATCH',
        headers: buildHeaders(identity, supabaseKey, 'return=representation'),
        body: JSON.stringify(updateData),
      });
    } catch (err) {
      throw new TreeRecordError('network', err instanceof Error ? err.message : 'Network request failed');
    }

    if (!res.ok) {
      await handleResponseError(res);
    }

    const persons = personsFromRows(await readRows(res));
    if (persons.length === 0) {
      throw new TreeRecordError(
        'not-authorized',
        'No Person was updated. Confirm you are allowed to edit this Person, then refresh and try again.'
      );
    }
    return { persons };
  };

  const editLink = async (params: EditLinkParams): Promise<ConfirmedRows> => {
    if (!identity.isAdmin) {
      throw new TreeRecordError('not-authorized', 'Only administrators can edit links.');
    }

    const payload: Record<string, unknown> = {};
    if (params.sourceId !== undefined) payload.source_node_id = params.sourceId;
    if (params.targetId !== undefined) payload.target_node_id = params.targetId;
    if (params.type !== undefined) payload.type = params.type;
    if (params.parentRole !== undefined) {
      payload.parent_role = params.type === 'parent' ? (params.parentRole ?? null) : null;
    }

    const lid = encodeURIComponent(params.id);
    let res: Response;
    try {
      res = await fetchFn(`${supabaseUrl}/rest/v1/links?id=eq.${lid}`, {
        method: 'PATCH',
        headers: buildHeaders(identity, supabaseKey, 'return=representation'),
        body: JSON.stringify(payload),
      });
    } catch (err) {
      throw new TreeRecordError('network', err instanceof Error ? err.message : 'Network request failed');
    }

    if (!res.ok) {
      await handleResponseError(res);
    }

    const links = kinshipLinksFromRows(await readRows(res));
    if (links.length === 0) {
      throw new TreeRecordError(
        'not-authorized',
        'No Kinship Link was updated. Confirm your account has role admin in the database, then refresh and try again.'
      );
    }
    return { links };
  };

  const removePerson = async (params: RemovePersonParams): Promise<ConfirmedRows> => {
    if (!identity.isAdmin) {
      throw new TreeRecordError('not-authorized', 'Only administrators can delete persons.');
    }

    let res: Response;
    try {
      res = await fetchFn(`${supabaseUrl}/rest/v1/rpc/admin_delete_node_secure`, {
        method: 'POST',
        headers: buildHeaders(identity, supabaseKey),
        body: JSON.stringify({ p_node_id: params.id }),
      });
    } catch (err) {
      throw new TreeRecordError('network', err instanceof Error ? err.message : 'Network request failed');
    }

    const text = await res.text().catch(() => '');
    if (!res.ok) {
      throw new TreeRecordError('network', parseErrorMessage(text, res.status), res.status);
    }

    const payload = parseRpcEnvelope(text);

    if (!payload.success) {
      throw new TreeRecordError(
        'not-authorized',
        payload.message || 'Could not delete this node. Confirm your account has role admin in the database.'
      );
    }

    // The Person is the one this call named; the Kinship Links are whatever the
    // FK cascade took with it, which only the database knows.
    return {
      removedPersonIds: [params.id],
      removedLinkIds: Array.isArray(payload.removed_link_ids)
        ? payload.removed_link_ids.map(String)
        : [],
    };
  };

  const removeLink = async (params: RemoveLinkParams): Promise<ConfirmedRows> => {
    if (!identity.isAdmin) {
      throw new TreeRecordError('not-authorized', 'Only administrators can delete links.');
    }

    const lid = encodeURIComponent(params.id);
    let res: Response;
    try {
      res = await fetchFn(`${supabaseUrl}/rest/v1/links?id=eq.${lid}`, {
        method: 'DELETE',
        headers: buildHeaders(identity, supabaseKey, 'return=representation'),
      });
    } catch (err) {
      throw new TreeRecordError('network', err instanceof Error ? err.message : 'Network request failed');
    }

    const text = await res.text().catch(() => '');
    if (!res.ok) {
      throw new TreeRecordError('network', parseErrorMessage(text, res.status), res.status);
    }

    let rows: unknown[] = [];
    try {
      rows = text ? (JSON.parse(text) as unknown[]) : [];
    } catch {
      rows = [];
    }

    // The request filtered on `id=eq.<params.id>`, so the rows say whether the
    // delete happened, never which row it was.
    if (rows.length === 0) {
      throw new TreeRecordError(
        'not-authorized',
        'No link was deleted. Confirm your account has role admin in the database, then refresh and try again.'
      );
    }

    return { removedLinkIds: [params.id] };
  };

  return {
    addPerson,
    addLink,
    editPerson,
    editLink,
    removePerson,
    removeLink,
  };
}
