-- =============================================================================
-- LIN-76: the gender of each existing Person, from the owner's corrected list.
--
-- Generated by scripts/person-gender/to-migration.ts from:
--   /Users/fahdbadran/Documents/CodeFB/osra/.gender-lists/persons-gender-prod.csv
-- 76 Persons: 34 male, 42 female. Persons left blank
-- in the list are not here and stay not recorded.
--
-- 1. Stores each gender, never overwriting one already recorded. An id this
--    database does not have updates nothing, so one file serves dev and prod.
--    A gender that disagrees with a recorded parent_role is refused by
--    trg_nodes_gender_agrees_with_parent_roles, and the whole migration fails.
-- 2. Fills every parent Kinship Link with no parent_role from the parent's
--    gender (the backfill: it must come after the genders, never before).
-- 3. Fails if any parent link still disagrees with its parent's gender.
--
-- Preview first with the read-only dry run the same script wrote.
-- =============================================================================

-- 1. The genders
WITH list(id, gender) AS (
  VALUES
    ('10000000-1000-4000-8000-00000000002e'::uuid, 'male'), -- Abdulfattah Zabalawi
    ('10000000-1000-4000-8000-00000000004c'::uuid, 'male'), -- Abdulfattah Zabalawi
    ('10000000-1000-4000-8000-000000000015'::uuid, 'male'), -- Abdulrazzaq Badran
    ('10000000-1000-4000-8000-000000000038'::uuid, 'male'), -- Adam Zabalawi
    ('10000000-1000-4000-8000-000000000022'::uuid, 'female'), -- Aisha Qassas
    ('10000000-1000-4000-8000-00000000003e'::uuid, 'female'), -- Aleen Abukhalaf
    ('10000000-1000-4000-8000-000000000049'::uuid, 'male'), -- Ali Okasha
    ('10000000-1000-4000-8000-00000000000c'::uuid, 'male'), -- Ammar Hajjaj
    ('10000000-1000-4000-8000-000000000029'::uuid, 'female'), -- Atika Badran
    ('10000000-1000-4000-8000-000000000034'::uuid, 'female'), -- Aya Zabalawi
    ('10000000-1000-4000-8000-000000000040'::uuid, 'male'), -- Ayman Okasha
    ('10000000-1000-4000-8000-00000000000b'::uuid, 'female'), -- Aysha Badran
    ('10000000-1000-4000-8000-000000000010'::uuid, 'male'), -- Badran Badran
    ('10000000-1000-4000-8000-000000000002'::uuid, 'female'), -- Baha Zabalawi
    ('10000000-1000-4000-8000-000000000001'::uuid, 'male'), -- Basel Badran
    ('10000000-1000-4000-8000-000000000014'::uuid, 'female'), -- Dana Badran
    ('10000000-1000-4000-8000-000000000009'::uuid, 'female'), -- Dareen Kutob
    ('10000000-1000-4000-8000-000000000032'::uuid, 'female'), -- Diala Zabalawi
    ('10000000-1000-4000-8000-000000000028'::uuid, 'female'), -- Ebreeza Badran
    ('10000000-1000-4000-8000-000000000041'::uuid, 'female'), -- Eman Zabalawi
    ('10000000-1000-4000-8000-000000000003'::uuid, 'male'), -- Fahd Badran
    ('10000000-1000-4000-8000-00000000001a'::uuid, 'female'), -- Farah Badran
    ('10000000-1000-4000-8000-00000000002d'::uuid, 'female'), -- Farah Zabalawi
    ('10000000-1000-4000-8000-00000000002b'::uuid, 'female'), -- Ghadeer Badran
    ('10000000-1000-4000-8000-000000000018'::uuid, 'female'), -- Hala Badran
    ('10000000-1000-4000-8000-000000000043'::uuid, 'female'), -- Hana Okasha
    ('10000000-1000-4000-8000-00000000001f'::uuid, 'male'), -- Hashim Shaban
    ('10000000-1000-4000-8000-00000000001b'::uuid, 'male'), -- Hisham Shaban
    ('10000000-1000-4000-8000-000000000016'::uuid, 'female'), -- Iftikhar Farekh
    ('10000000-1000-4000-8000-00000000000f'::uuid, 'male'), -- Issa Hajjaj
    ('10000000-1000-4000-8000-000000000024'::uuid, 'male'), -- Jamal Badran
    ('10000000-1000-4000-8000-00000000003a'::uuid, 'female'), -- Jihad Zabalawi
    ('10000000-1000-4000-8000-000000000020'::uuid, 'male'), -- Kareem Shaban
    ('10000000-1000-4000-8000-00000000000d'::uuid, 'male'), -- Karim Hajjaj
    ('10000000-1000-4000-8000-000000000008'::uuid, 'male'), -- Kazem Kutob
    ('10000000-1000-4000-8000-000000000025'::uuid, 'male'), -- Khairi Badran
    ('10000000-1000-4000-8000-000000000037'::uuid, 'female'), -- Kholoud Bsaiso
    ('10000000-1000-4000-8000-000000000048'::uuid, 'female'), -- Laila Okasha
    ('10000000-1000-4000-8000-00000000001e'::uuid, 'female'), -- Lana Bawaneh
    ('10000000-1000-4000-8000-000000000007'::uuid, 'female'), -- Layan Kutob
    ('10000000-1000-4000-8000-000000000033'::uuid, 'female'), -- Leen Zabalawi
    ('10000000-1000-4000-8000-000000000045'::uuid, 'male'), -- Louai Okasha
    ('10000000-1000-4000-8000-000000000019'::uuid, 'female'), -- Maha Alami
    ('10000000-1000-4000-8000-000000000004'::uuid, 'female'), -- May Badran
    ('10000000-1000-4000-8000-000000000044'::uuid, 'female'), -- Maya Okasha
    ('10000000-1000-4000-8000-000000000005'::uuid, 'male'), -- Mazen Kutob
    ('10000000-1000-4000-8000-000000000021'::uuid, 'male'), -- Mohammad Hasan Badran
    ('10000000-1000-4000-8000-00000000004b'::uuid, 'male'), -- Mohammad Zabalawi
    ('10000000-1000-4000-8000-00000000003d'::uuid, 'male'), -- Mohammed Abukhalaf
    ('10000000-1000-4000-8000-000000000030'::uuid, 'male'), -- Mohammed Zabalawi
    ('10000000-1000-4000-8000-000000000013'::uuid, 'female'), -- Nada Badran
    ('10000000-1000-4000-8000-000000000042'::uuid, 'female'), -- Nada Okasha
    ('10000000-1000-4000-8000-000000000027'::uuid, 'female'), -- Naheeza Badran
    ('10000000-1000-4000-8000-000000000039'::uuid, 'male'), -- Nasser Abukhalaf
    ('10000000-1000-4000-8000-000000000035'::uuid, 'female'), -- Noor Zabalawi
    ('10000000-1000-4000-8000-00000000000e'::uuid, 'female'), -- Noora Hajjaj
    ('10000000-1000-4000-8000-000000000031'::uuid, 'female'), -- Ola Fiedi
    ('10000000-1000-4000-8000-000000000017'::uuid, 'male'), -- Omar Badran
    ('10000000-1000-4000-8000-000000000026'::uuid, 'female'), -- Pakiza Badran
    ('10000000-1000-4000-8000-000000000011'::uuid, 'female'), -- Randa Pharoan
    ('10000000-1000-4000-8000-000000000012'::uuid, 'female'), -- Rasha Badran
    ('10000000-1000-4000-8000-000000000023'::uuid, 'male'), -- Saadi Badran
    ('10000000-1000-4000-8000-000000000046'::uuid, 'female'), -- Salam Zabalawi
    ('10000000-1000-4000-8000-000000000047'::uuid, 'female'), -- Salma Okasha
    ('10000000-1000-4000-8000-00000000004a'::uuid, 'female'), -- Samira Zabalawi
    ('10000000-1000-4000-8000-00000000001c'::uuid, 'male'), -- Seif Shaban
    ('10000000-1000-4000-8000-000000000006'::uuid, 'female'), -- Shatha Malhis
    ('10000000-1000-4000-8000-00000000003f'::uuid, 'male'), -- Taha Abukhalaf
    ('10000000-1000-4000-8000-00000000000a'::uuid, 'female'), -- Taleen Kutob
    ('10000000-1000-4000-8000-000000000036'::uuid, 'male'), -- Yasser Zabalawi
    ('10000000-1000-4000-8000-00000000002c'::uuid, 'male'), -- Yehia Zabalawi
    ('10000000-1000-4000-8000-00000000003c'::uuid, 'male'), -- Younes Abukhalaf
    ('10000000-1000-4000-8000-00000000003b'::uuid, 'male'), -- Zaid Abukhalaf
    ('10000000-1000-4000-8000-00000000002a'::uuid, 'male'), -- Zakaria Zabalawi
    ('10000000-1000-4000-8000-00000000001d'::uuid, 'female'), -- Zeina Shaban
    ('10000000-1000-4000-8000-00000000002f'::uuid, 'female')  -- Zeina Zabalawi
)
UPDATE public.nodes AS n
SET gender = list.gender
FROM list
WHERE n.id = list.id
  AND n.gender IS NULL;

-- 2. The backfill: empty parent_role values from the parent's gender
UPDATE public.links AS l
SET parent_role = public.parent_role_for_gender(n.gender)
FROM public.nodes AS n
WHERE l.type = 'parent'
  AND l.source_node_id = n.id
  AND l.parent_role IS NULL
  AND n.gender IS NOT NULL;

-- 3. Every parent link from a Person with a gender has the matching role
DO $$
DECLARE
  v_bad integer;
BEGIN
  SELECT count(*) INTO v_bad
  FROM public.links l
  JOIN public.nodes n ON n.id = l.source_node_id
  WHERE l.type = 'parent'
    AND n.gender IS NOT NULL
    AND l.parent_role IS DISTINCT FROM public.parent_role_for_gender(n.gender);
  IF v_bad > 0 THEN
    RAISE EXCEPTION '% parent Kinship Links disagree with their parent''s gender', v_bad;
  END IF;
END $$;
